# Generated by Django 2.0.4 on 2018-04-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_response_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='answer',
        ),
        migrations.AddField(
            model_name='response',
            name='answer',
            field=models.ManyToManyField(to='feedback.Answer'),
        ),
    ]
